name: Living
options:
  bundleIdPrefix: com.living
  deploymentTarget:
    iOS: "17.0"
  xcodeVersion: "15.0"

configs:
  Debug: debug
  Release: release

settings:
  base:
    SWIFT_VERSION: "5.9"
    GENERATE_INFOPLIST_FILE: YES
  configs:
    Debug:
      PRODUCT_BUNDLE_IDENTIFIER: com.living.app.dev
    Release:
      PRODUCT_BUNDLE_IDENTIFIER: com.living.app

targets:
  Living:
    type: application
    platform: iOS
    sources:
      - Living
    settings:
      base:
        INFOPLIST_KEY_UIApplicationSceneManifest_Generation: YES
        INFOPLIST_KEY_UIApplicationSupportsIndirectInputEvents: YES
        INFOPLIST_KEY_UILaunchScreen_Generation: YES
        INFOPLIST_KEY_UISupportedInterfaceOrientations_iPhone: UIInterfaceOrientationPortrait
        INFOPLIST_KEY_CFBundleDisplayName: Living
    postBuildScripts:
      - name: Copy Firebase Config
        script: |
          if [ "${CONFIGURATION}" == "Debug" ]; then
            cp "${PROJECT_DIR}/Living/Firebase/Dev/GoogleService-Info.plist" "${BUILT_PRODUCTS_DIR}/${PRODUCT_NAME}.app/GoogleService-Info.plist"
          else
            cp "${PROJECT_DIR}/Living/Firebase/Prod/GoogleService-Info.plist" "${BUILT_PRODUCTS_DIR}/${PRODUCT_NAME}.app/GoogleService-Info.plist"
          fi
        basedOnDependencyAnalysis: false
    dependencies:
      - package: firebase-ios-sdk
        product: FirebaseFirestore
      - package: firebase-ios-sdk
        product: FirebaseAuth
      - package: KeychainAccess

packages:
  firebase-ios-sdk:
    url: https://github.com/firebase/firebase-ios-sdk
    from: "10.0.0"
  KeychainAccess:
    url: https://github.com/kishikawakatsumi/KeychainAccess
    from: "4.2.2"
